// <auto-generated />
using System;
using Epsic_Cave_A_Vin_Ethan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epsic_Cave_A_Vin_Ethan.Migrations
{
    [DbContext(typeof(EpsicCaveAVinDataContext))]
    [Migration("20210114082633_InitialCreate10")]
    partial class InitialCreate10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Epsic_Cave_A_Vin_Ethan.Models.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaveId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricePerBottle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Typevin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaveId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Bottles");
                });

            modelBuilder.Entity("Epsic_Cave_A_Vin_Ethan.Models.Cave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Caves");
                });

            modelBuilder.Entity("Epsic_Cave_A_Vin_Ethan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Epsic_Cave_A_Vin_Ethan.Models.Bottle", b =>
                {
                    b.HasOne("Epsic_Cave_A_Vin_Ethan.Models.Cave", "Cave")
                        .WithMany()
                        .HasForeignKey("CaveId");

                    b.HasOne("Epsic_Cave_A_Vin_Ethan.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cave");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
